[2024-04-30T18:07:45.678+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T18:07:45.725+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataset_consumes_1_and_2.consuming_2 manual__2024-04-30T18:07:40.930172+00:00 [queued]>
[2024-04-30T18:07:45.736+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataset_consumes_1_and_2.consuming_2 manual__2024-04-30T18:07:40.930172+00:00 [queued]>
[2024-04-30T18:07:45.737+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T18:07:45.761+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): consuming_2> on 2024-04-30 18:07:40.930172+00:00
[2024-04-30T18:07:45.778+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=962) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T18:07:45.784+0000] {standard_task_runner.py:63} INFO - Started process 964 to run task
[2024-04-30T18:07:45.784+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dataset_consumes_1_and_2', 'consuming_2', 'manual__2024-04-30T18:07:40.930172+00:00', '--job-id', '29', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_datasets.py', '--cfg-path', '/tmp/tmpjrbptm0z']
[2024-04-30T18:07:45.791+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask consuming_2
[2024-04-30T18:07:45.924+0000] {task_command.py:426} INFO - Running <TaskInstance: dataset_consumes_1_and_2.consuming_2 manual__2024-04-30T18:07:40.930172+00:00 [running]> on host 85d72ecba59d
[2024-04-30T18:07:46.312+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dataset_consumes_1_and_2' AIRFLOW_CTX_TASK_ID='consuming_2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T18:07:40.930172+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T18:07:40.930172+00:00'
[2024-04-30T18:07:46.331+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T18:07:46.359+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-30T18:07:46.363+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2024-04-30T18:07:46.433+0000] {subprocess.py:86} INFO - Output:
[2024-04-30T18:07:51.493+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-30T18:07:51.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T18:07:51.528+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1564: RemovedInAirflow3Warning: Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated.
  context["ti"].xcom_push(key=key, value=value, execution_date=execution_date)

[2024-04-30T18:07:51.555+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dataset_consumes_1_and_2, task_id=consuming_2, execution_date=20240430T180740, start_date=20240430T180745, end_date=20240430T180751
[2024-04-30T18:07:51.615+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T18:07:51.642+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T18:07:51.645+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
