[2024-04-28T06:29:21.454+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T06:29:21.566+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-28T06:29:08.416057+00:00 [queued]>
[2024-04-28T06:29:21.623+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-28T06:29:08.416057+00:00 [queued]>
[2024-04-28T06:29:21.628+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T06:29:21.690+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-04-28 06:29:08.416057+00:00
[2024-04-28T06:29:21.709+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T06:29:21.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-04-28T06:29:08.416057+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp_x4zvgyd']
[2024-04-28T06:29:21.715+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2024-04-28T06:29:21.715+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask extract_data_from_wikipedia
[2024-04-28T06:29:21.855+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-28T06:29:08.416057+00:00 [running]> on host 22f5aca04ff7
[2024-04-28T06:29:22.059+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T06:29:08.416057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T06:29:08.416057+00:00'
[2024-04-28T06:29:22.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T06:29:22.065+0000] {logging_mixin.py:188} INFO - Getting wikipedia page... None
[2024-04-28T06:29:22.069+0000] {logging_mixin.py:188} INFO - An error occured: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2024-04-28T06:29:22.071+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T06:29:22.072+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 51, in extract_wikipedia_data
    rows = get_wikipedia_data(html)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 26, in get_wikipedia_data
    soup = BeautifulSoup(html, 'html.parser')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
[2024-04-28T06:29:22.099+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20240428T062908, start_date=20240428T062921, end_date=20240428T062922
[2024-04-28T06:29:22.159+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 179 for task extract_data_from_wikipedia (object of type 'NoneType' has no len(); 230)
[2024-04-28T06:29:22.214+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T06:29:22.274+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T06:29:22.296+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
